#!/bin/sh

# 編集されたファイルを抽出してsrcにコンバートする
BRANCH_NAME=`git rev-parse --abbrev-ref HEAD`
MODIFYED_FILES=`git diff --name-only origin/$BRANCH_NAME`

if [ ! $MODIFYED_FILES = '' ]; then
    sfdx force:source:convert -d src
fi